AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS infrastructure for Testing, Staging, and Production environments with public subnets.'

Parameters:
  EnvironmentName:
    Type: String
    AllowedValues:
      - Testing
      - Staging
      - Production
    Description: 'Select the environment to deploy the resources.'

Mappings:
  EnvironmentCidrBlocks:
    Testing:
      VpcCidr: '10.0.0.0/16'
      Subnet1Cidr: '10.0.1.0/24'
      Subnet2Cidr: '10.0.2.0/24'
      Subnet3Cidr: '10.0.3.0/24'
    Staging:
      VpcCidr: '10.1.0.0/16'
      Subnet1Cidr: '10.1.1.0/24'
      Subnet2Cidr: '10.1.2.0/24'
      Subnet3Cidr: '10.1.3.0/24'
    Production:
      VpcCidr: '10.2.0.0/16'
      Subnet1Cidr: '10.2.1.0/24'
      Subnet2Cidr: '10.2.2.0/24'
      Subnet3Cidr: '10.2.3.0/24'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [EnvironmentCidrBlocks, !Ref EnvironmentName, VpcCidr]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-VPC'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-IGW'

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [EnvironmentCidrBlocks, !Ref EnvironmentName, Subnet1Cidr]
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-PublicSubnet1'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [EnvironmentCidrBlocks, !Ref EnvironmentName, Subnet2Cidr]
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-PublicSubnet2'

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [EnvironmentCidrBlocks, !Ref EnvironmentName, Subnet3Cidr]
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-PublicSubnet3'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-RouteTable'

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Association of Subnets to Route Table
  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  SubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet3
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPCID:
    Description: "ID of the VPC created for the selected environment."
    Value: !Ref VPC
    Export:
      Name: !Sub "${EnvironmentName}-VPCID"

  PublicSubnet1ID:
    Description: "ID of the first Public Subnet in the selected environment."
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${EnvironmentName}-PublicSubnet1ID"

  PublicSubnet2ID:
    Description: "ID of the second Public Subnet in the selected environment."
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${EnvironmentName}-PublicSubnet2ID"

  PublicSubnet3ID:
    Description: "ID of the third Public Subnet in the selected environment."
    Value: !Ref PublicSubnet3
    Export:
      Name: !Sub "${EnvironmentName}-PublicSubnet3ID"